project_id = "trcnfauhlnfkmhlwprwn"

[functions.bling-oauth]
verify_jwt = false

[functions.bling-config]
verify_jwt = false

[functions.bling-oauth-callback]
verify_jwt = false

[functions.sync-ncm]
verify_jwt = false

[functions.buscar-ncm]
verify_jwt = false

[functions.bling-proxy]
verify_jwt = false
